// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createResult = `-- name: CreateResult :execresult
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32
	MeetID    int32
	Time      string
	Place     sql.NullInt32
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, personal_record, events, created_at, updated_at
FROM athletes
ORDER BY name
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location, description, created_at, updated_at
FROM meets
ORDER BY date
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, personal_record, events, created_at, updated_at
FROM athletes
WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAthleteResults = `-- name: GetAthleteResults :many
SELECT
    r.id,
    r.athlete_id,
    r.meet_id,
    r.event,
    r.time,
    r.place,
    r.created_at,
    m.name as meet_name,
    m.date as meet_date
FROM results r
JOIN meets m ON r.meet_id = m.id
WHERE r.athlete_id = ?
ORDER BY m.date DESC
`

type GetAthleteResultsRow struct {
	ID        int32
	AthleteID int32
	MeetID    int32
	Event     sql.NullString
	Time      string
	Place     sql.NullInt32
	CreatedAt sql.NullTime
	MeetName  string
	MeetDate  time.Time
}

func (q *Queries) GetAthleteResults(ctx context.Context, athleteID int32) ([]GetAthleteResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAthleteResults, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAthleteResultsRow
	for rows.Next() {
		var i GetAthleteResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Event,
			&i.Time,
			&i.Place,
			&i.CreatedAt,
			&i.MeetName,
			&i.MeetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetResults = `-- name: GetMeetResults :many
SELECT
    r.id,
    r.athlete_id,
    r.meet_id,
    r.event,
    r.time,
    r.place,
    r.created_at,
    a.name as athlete_name
FROM results r
JOIN athletes a ON r.athlete_id = a.id
WHERE r.meet_id = ?
ORDER BY r.place
`

type GetMeetResultsRow struct {
	ID          int32
	AthleteID   int32
	MeetID      int32
	Event       sql.NullString
	Time        string
	Place       sql.NullInt32
	CreatedAt   sql.NullTime
	AthleteName string
}

func (q *Queries) GetMeetResults(ctx context.Context, meetID int32) ([]GetMeetResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetResults, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetResultsRow
	for rows.Next() {
		var i GetMeetResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Event,
			&i.Time,
			&i.Place,
			&i.CreatedAt,
			&i.AthleteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTenFastestTimes = `-- name: GetTopTenFastestTimes :many
SELECT
    r.id,
    r.time,
    r.place,
    a.id as athlete_id,
    a.name as athlete_name,
    a.grade as athlete_grade,
    m.id as meet_id,
    m.name as meet_name,
    m.date as meet_date
FROM results r
JOIN athletes a ON r.athlete_id = a.id
JOIN meets m ON r.meet_id = m.id
ORDER BY r.time ASC
LIMIT 10
`

type GetTopTenFastestTimesRow struct {
	ID           int32
	Time         string
	Place        sql.NullInt32
	AthleteID    int32
	AthleteName  string
	AthleteGrade int32
	MeetID       int32
	MeetName     string
	MeetDate     time.Time
}

func (q *Queries) GetTopTenFastestTimes(ctx context.Context) ([]GetTopTenFastestTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTenFastestTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTenFastestTimesRow
	for rows.Next() {
		var i GetTopTenFastestTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Place,
			&i.AthleteID,
			&i.AthleteName,
			&i.AthleteGrade,
			&i.MeetID,
			&i.MeetName,
			&i.MeetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
